### ISSUE TITLE
按readme操作，有错误，没跑起来。麻烦帮忙看看是哪里的问题。

### ISSUE THREAD

**Issue by JaySlamer** [TurtleZhong/AVP-SLAM-SIM#1]
![图片](https://user-images.githubusercontent.com/12229227/105435347-29bd7a80-5c98-11eb-976f-c1d16e1a7d59.png)

**Comment by JaySlamer** [comment]
![图片](https://user-images.githubusercontent.com/12229227/105436247-df3cfd80-5c99-11eb-90f1-e80a6127e099.png)

octomap的问题是没安装。现在还剩一个gazebo节点launch不起来的问题。查了一下，相应的文件路径都在。

**Comment by TurtleZhong** [comment]
> ![图片](https://user-images.githubusercontent.com/12229227/105436247-df3cfd80-5c99-11eb-90f1-e80a6127e099.png)
> 
> octomap的问题是没安装。现在还剩一个gazebo节点launch不起来的问题。查了一下，相应的文件路径都在。

好的，我到时候查看一下具体问题，octomap那个应该是我rviz忘记删干净了，我看报错像是gazebo的问题啊，我到时候去一台干净的机子上测试一下

**Comment by TurtleZhong** [comment]
> ![图片](https://user-images.githubusercontent.com/12229227/105436247-df3cfd80-5c99-11eb-90f1-e80a6127e099.png)
> 
> octomap的问题是没安装。现在还剩一个gazebo节点launch不起来的问题。查了一下，相应的文件路径都在。

您好，我这边已经把rviz清理干净了，另外你关注一下gazebo有没有其它报错，从报错上来看，好像是你gazebo的问题，我重新push了代码和更新了readme，readme添加了离线下载好模型文件然后放到gazebo目录的方式，如果再有问题，后期可能会提供一个docker环境。

**Comment by JaySlamer** [comment]
> > ![图片](https://user-images.githubusercontent.com/12229227/105436247-df3cfd80-5c99-11eb-90f1-e80a6127e099.png)
> > octomap的问题是没安装。现在还剩一个gazebo节点launch不起来的问题。查了一下，相应的文件路径都在。
> 
> 您好，我这边已经把rviz清理干净了，另外你关注一下gazebo有没有其它报错，从报错上来看，好像是你gazebo的问题，我重新push了代码和更新了readme，readme添加了离线下载好模型文件然后放到gazebo目录的方式，如果再有问题，后期可能会提供一个docker环境。

您说的对，这基本可以确定是我这边环境的问题。可能是因为我在公司用的是虚拟机。

**Comment by TurtleZhong** [comment]
应该是环境问题，后续会以husky的仿真环境搭建，并上传docker镜像
